### ISSUE TITLE
Data Description of Kitchen Franka

### ISSUE THREAD

**Issue by liubaoryol** [notmahi/bet#10]
Hi!
I'm trying to make sense of the data that you have used in detail.
I have looked into[ Franka-Kitchen documentation](https://robotics.farama.org/envs/franka_kitchen/franka_kitchen/)
however there are some differences that I would like to understand. 
For instance, it has an observation of 59 instead of 60 , and also the code of this repo has the following block in `envs/kitchen/__init__.py`:
```
OBS_ELEMENT_INDICES = {
    "bottom burner": np.array([11, 12]),
    "top burner": np.array([15, 16]),
    "light switch": np.array([17, 18]),
    "slide cabinet": np.array([19]),
    "hinge cabinet": np.array([20, 21]),
    "microwave": np.array([22]),
    "kettle": np.array([23, 24, 25, 26, 27, 28, 29]),
}
```

Where can I find the meaning of each entry of observation?

Thank you so much!

**Comment by jeffacce** [comment]
Hi there!

If I recall correctly, the first 30 elements contains the environment state, and the last 30 elements contains the goal state I believe. The first 9 elements should be the robot states, and elements [9:30] should be object states I think.

Also see this in d4rl: https://github.com/Farama-Foundation/D4RL/blob/cf0efbd75a9e05f34dfee2f566e163abfa512485/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py#L130
