### ISSUE TITLE
observation dimension of 'multimodal_push_masks.npy'

### ISSUE THREAD

**Issue by xavihart** [notmahi/bet#6]
why the observation dimension of 'bet_data_release/blockpush/multimodal_push_masks.npy' is (1000, 201, 16), and how can we get the last axis 16?

**Comment by chrislgarry** [comment]
Bump!

**Comment by jeffacce** [comment]
Hi there,

You can find the observation dims here:

https://github.com/notmahi/bet/blob/3d9d42352c0a0a6fb170369e95dde4ec3cfea951/envs/block_pushing/block_pushing_multimodal.py#L339-L350

```
block_translation             (0, 1)
block_orientation             (2)
block2_translation            (3, 4)
block2_orientation            (5)
effector_translation          (6, 7)
effector_target_translation   (8, 9)
target_translation            (10, 11)
target_orientation            (12)
target2_translation           (13, 14)
target2_orientation           (15)
```
