### ISSUE TITLE
Data permission

### ISSUE THREAD

**Issue by gftww** [notmahi/bet#7]
Thank you for your awesome work!
However, when I tried to download the dataset( https://osf.io/983qz/), I got a permission error as follows:
![image](https://github.com/notmahi/bet/assets/100254421/dabd4447-0ab5-4a08-8e5e-3b54f45f02fa)
Please help me.
Best wishes.

**Comment by paolo-viceconte** [comment]
Hi, I get the very same issue when trying to request access to the dataset on OSF:

![error_OSF](https://github.com/notmahi/bet/assets/41757826/e25f545f-bd19-4bba-b402-3e7880a503aa)

Is there any alternative way to get the training datasets? 
Thank you a lot in advance!

**Comment by paolo-viceconte** [comment]
I contacted `support@osf.io` as suggested in the error message, and I received this answer:

> It appears that project was caught in our spam filter. Thanks for alerting us, the project is public again. Don't hesitate to reach out in the future with additional questions or feedback.

I can see the dataset now!

**Comment by notmahi** [comment]
Thank you for catching and resolving this issue, closing it since there isn't anything else for me to do.
