### ISSUE TITLE
Request of asset folder for pybullet environment

### ISSUE THREAD

**Issue by baoyufuyou** [notmahi/bet#9]
Dear Nur Muhammad (Mahi) Shafiullah and Zichen Jeff Cui,
Thanks a lot for sharing your work into community. May I ask did you open source the asset folder for the xarm environment? Is that possible to share the folder to me? Thanks a lot!

Best regards,
Lei

**Comment by notmahi** [comment]
Hi, all the assets you are looking for are already open source and should already be there in this folder: https://github.com/notmahi/bet/tree/main/envs/assets . Are there any particular reason you're asking for them?

**Comment by baoyufuyou** [comment]
@notmahi I didn't see it. :) Thanks!
